[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements-deploy.txt"

[deploy]
startCommand = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
restartPolicyType = "ON_FAILURE"